#!/usr/bin/env bash
if [ -z "$1" ]; then
	docker-compose exec --user www-data apache gulp --cwd /var/www/html/vendor/snowdog/frontools/
else
	docker-compose exec --user www-data apache gulp --cwd /var/www/html/vendor/snowdog/frontools/ $1
fi