#!/usr/bin/env bash
docker-compose exec --user www-data apache yarn --cwd /var/www/html/vendor/snowdog/frontools/
docker-compose exec --user www-data apache gulp --cwd /var/www/html/vendor/snowdog/frontools/ setup